### ISSUE TITLE
[Spring boot - AWS DocDB] io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already

### ISSUE THREAD

**Issue by hungbang** [BarathArivazhagan/aws-documentdb#2]
I am getting the error below when trying to connect amazon DocumentDB from spring boot with ca-bundle cert. 
I copied your implementation into Application.java.

```
Spring boot version: 2.3.7.RELEASE
Mongo driver: 4.0.5
```

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'noneService' defined in file [/app/classes/ai/teemo/teemoservice/service/NoneService.class]: Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@48af5f38. Client view of cluster state is {type=REPLICA_SET, servers=[{address=twinci-docdb-prod.cluster-cxiyqoolhj3e.ap-southeast-1.docdb.amazonaws.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@48af5f38. Client view of cluster state is {type=REPLICA_SET, servers=[{address=twinci-docdb-prod.cluster-cxiyqoolhj3e.ap-southeast-1.docdb.amazonaws.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already}}]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)
        ... 34 common frames omitted
Caused by: org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@48af5f38. Client view of cluster state is {type=REPLICA_SET, servers=[{address=twinci-docdb-prod.cluster-cxiyqoolhj3e.ap-southeast-1.docdb.amazonaws.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@48af5f38. Client view of cluster state is {type=REPLICA_SET, servers=[{address=twinci-docdb-prod.cluster-cxiyqoolhj3e.ap-southeast-1.docdb.amazonaws.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already}}]
        at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:88)
```

it will be better if you got the same in the past. Thank you in advance.

**Comment by hungbang** [comment]
@BarathArivazhagan I have created a sample to connect aws docdb from spring boot with SSL enabled. Please take a look at here https://github.com/hungbang/spring-boot-aws-docdb
